package com.atlanta.educatic.pojo;
// Generated 14/01/2016 06:39:31 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Curso generated by hbm2java
 */
public class Curso  implements java.io.Serializable {


     private int id;
     private Tablamaestra tablamaestraByEstado;
     private Tablamaestra tablamaestraByTipoCurso;
     private String denominacion;
     private String descripcion;
     private Integer observacion;
     private Set gradoCursos = new HashSet(0);

    public Curso() {
    }

	
    public Curso(int id, Tablamaestra tablamaestraByTipoCurso, String denominacion) {
        this.id = id;
        this.tablamaestraByTipoCurso = tablamaestraByTipoCurso;
        this.denominacion = denominacion;
    }
    public Curso(int id, Tablamaestra tablamaestraByEstado, Tablamaestra tablamaestraByTipoCurso, String denominacion, String descripcion, Integer observacion, Set gradoCursos) {
       this.id = id;
       this.tablamaestraByEstado = tablamaestraByEstado;
       this.tablamaestraByTipoCurso = tablamaestraByTipoCurso;
       this.denominacion = denominacion;
       this.descripcion = descripcion;
       this.observacion = observacion;
       this.gradoCursos = gradoCursos;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Tablamaestra getTablamaestraByEstado() {
        return this.tablamaestraByEstado;
    }
    
    public void setTablamaestraByEstado(Tablamaestra tablamaestraByEstado) {
        this.tablamaestraByEstado = tablamaestraByEstado;
    }
    public Tablamaestra getTablamaestraByTipoCurso() {
        return this.tablamaestraByTipoCurso;
    }
    
    public void setTablamaestraByTipoCurso(Tablamaestra tablamaestraByTipoCurso) {
        this.tablamaestraByTipoCurso = tablamaestraByTipoCurso;
    }
    public String getDenominacion() {
        return this.denominacion;
    }
    
    public void setDenominacion(String denominacion) {
        this.denominacion = denominacion;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Integer getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(Integer observacion) {
        this.observacion = observacion;
    }
    public Set getGradoCursos() {
        return this.gradoCursos;
    }
    
    public void setGradoCursos(Set gradoCursos) {
        this.gradoCursos = gradoCursos;
    }




}


