package com.atlanta.educatic.pojo;
// Generated 14/01/2016 06:39:31 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Institucion generated by hbm2java
 */
public class Institucion  implements java.io.Serializable {


     private int id;
     private Tablamaestra tablamaestra;
     private String nombreEntidad;
     private String direccion;
     private String observacion;
     private String telefono1;
     private String telefono2;
     private Set docentes = new HashSet(0);

    public Institucion() {
    }

	
    public Institucion(int id, Tablamaestra tablamaestra, String nombreEntidad, String direccion) {
        this.id = id;
        this.tablamaestra = tablamaestra;
        this.nombreEntidad = nombreEntidad;
        this.direccion = direccion;
    }
    public Institucion(int id, Tablamaestra tablamaestra, String nombreEntidad, String direccion, String observacion, String telefono1, String telefono2, Set docentes) {
       this.id = id;
       this.tablamaestra = tablamaestra;
       this.nombreEntidad = nombreEntidad;
       this.direccion = direccion;
       this.observacion = observacion;
       this.telefono1 = telefono1;
       this.telefono2 = telefono2;
       this.docentes = docentes;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Tablamaestra getTablamaestra() {
        return this.tablamaestra;
    }
    
    public void setTablamaestra(Tablamaestra tablamaestra) {
        this.tablamaestra = tablamaestra;
    }
    public String getNombreEntidad() {
        return this.nombreEntidad;
    }
    
    public void setNombreEntidad(String nombreEntidad) {
        this.nombreEntidad = nombreEntidad;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public String getTelefono1() {
        return this.telefono1;
    }
    
    public void setTelefono1(String telefono1) {
        this.telefono1 = telefono1;
    }
    public String getTelefono2() {
        return this.telefono2;
    }
    
    public void setTelefono2(String telefono2) {
        this.telefono2 = telefono2;
    }
    public Set getDocentes() {
        return this.docentes;
    }
    
    public void setDocentes(Set docentes) {
        this.docentes = docentes;
    }




}


