package com.atlanta.educatic.pojo;
// Generated 14/01/2016 06:39:31 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Modalidadingreso generated by hbm2java
 */
public class Modalidadingreso  implements java.io.Serializable {


     private int id;
     private Tablamaestra tablamaestra;
     private String denominacion;
     private String descripcion;
     private String observacion;
     private Set matriculas = new HashSet(0);

    public Modalidadingreso() {
    }

	
    public Modalidadingreso(int id) {
        this.id = id;
    }
    public Modalidadingreso(int id, Tablamaestra tablamaestra, String denominacion, String descripcion, String observacion, Set matriculas) {
       this.id = id;
       this.tablamaestra = tablamaestra;
       this.denominacion = denominacion;
       this.descripcion = descripcion;
       this.observacion = observacion;
       this.matriculas = matriculas;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Tablamaestra getTablamaestra() {
        return this.tablamaestra;
    }
    
    public void setTablamaestra(Tablamaestra tablamaestra) {
        this.tablamaestra = tablamaestra;
    }
    public String getDenominacion() {
        return this.denominacion;
    }
    
    public void setDenominacion(String denominacion) {
        this.denominacion = denominacion;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public Set getMatriculas() {
        return this.matriculas;
    }
    
    public void setMatriculas(Set matriculas) {
        this.matriculas = matriculas;
    }




}


