package com.atlanta.educatic.pojo;
// Generated 14/01/2016 06:39:31 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Permiso generated by hbm2java
 */
public class Permiso  implements java.io.Serializable {


     private int id;
     private Tablamaestra tablamaestra;
     private String denominacion;
     private Set usuarioPermisos = new HashSet(0);

    public Permiso() {
    }

	
    public Permiso(int id, Tablamaestra tablamaestra, String denominacion) {
        this.id = id;
        this.tablamaestra = tablamaestra;
        this.denominacion = denominacion;
    }
    public Permiso(int id, Tablamaestra tablamaestra, String denominacion, Set usuarioPermisos) {
       this.id = id;
       this.tablamaestra = tablamaestra;
       this.denominacion = denominacion;
       this.usuarioPermisos = usuarioPermisos;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Tablamaestra getTablamaestra() {
        return this.tablamaestra;
    }
    
    public void setTablamaestra(Tablamaestra tablamaestra) {
        this.tablamaestra = tablamaestra;
    }
    public String getDenominacion() {
        return this.denominacion;
    }
    
    public void setDenominacion(String denominacion) {
        this.denominacion = denominacion;
    }
    public Set getUsuarioPermisos() {
        return this.usuarioPermisos;
    }
    
    public void setUsuarioPermisos(Set usuarioPermisos) {
        this.usuarioPermisos = usuarioPermisos;
    }




}


