package com.atlanta.educatic.pojo;
// Generated 14/01/2016 06:39:31 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private int id;
     private Tablamaestra tablamaestra;
     private String nombre;
     private String apaterno;
     private String amaterno;
     private String dni;
     private String direccion;
     private int edad;
     private byte sexo;
     private String observacion;
     private int idUsuario;
     private Set estudiantes = new HashSet(0);
     private Set telefonos = new HashSet(0);
     private Set docentes = new HashSet(0);
     private Set archivoimagens = new HashSet(0);
     private Set apoderados = new HashSet(0);
     private Set usuarios = new HashSet(0);
     private Set tutors = new HashSet(0);

    public Persona() {
    }

	
    public Persona(int id, Tablamaestra tablamaestra, String nombre, String apaterno, String amaterno, String dni, String direccion, int edad, byte sexo, int idUsuario) {
        this.id = id;
        this.tablamaestra = tablamaestra;
        this.nombre = nombre;
        this.apaterno = apaterno;
        this.amaterno = amaterno;
        this.dni = dni;
        this.direccion = direccion;
        this.edad = edad;
        this.sexo = sexo;
        this.idUsuario = idUsuario;
    }
    public Persona(int id, Tablamaestra tablamaestra, String nombre, String apaterno, String amaterno, String dni, String direccion, int edad, byte sexo, String observacion, int idUsuario, Set estudiantes, Set telefonos, Set docentes, Set archivoimagens, Set apoderados, Set usuarios, Set tutors) {
       this.id = id;
       this.tablamaestra = tablamaestra;
       this.nombre = nombre;
       this.apaterno = apaterno;
       this.amaterno = amaterno;
       this.dni = dni;
       this.direccion = direccion;
       this.edad = edad;
       this.sexo = sexo;
       this.observacion = observacion;
       this.idUsuario = idUsuario;
       this.estudiantes = estudiantes;
       this.telefonos = telefonos;
       this.docentes = docentes;
       this.archivoimagens = archivoimagens;
       this.apoderados = apoderados;
       this.usuarios = usuarios;
       this.tutors = tutors;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Tablamaestra getTablamaestra() {
        return this.tablamaestra;
    }
    
    public void setTablamaestra(Tablamaestra tablamaestra) {
        this.tablamaestra = tablamaestra;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApaterno() {
        return this.apaterno;
    }
    
    public void setApaterno(String apaterno) {
        this.apaterno = apaterno;
    }
    public String getAmaterno() {
        return this.amaterno;
    }
    
    public void setAmaterno(String amaterno) {
        this.amaterno = amaterno;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public int getEdad() {
        return this.edad;
    }
    
    public void setEdad(int edad) {
        this.edad = edad;
    }
    public byte getSexo() {
        return this.sexo;
    }
    
    public void setSexo(byte sexo) {
        this.sexo = sexo;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Set getEstudiantes() {
        return this.estudiantes;
    }
    
    public void setEstudiantes(Set estudiantes) {
        this.estudiantes = estudiantes;
    }
    public Set getTelefonos() {
        return this.telefonos;
    }
    
    public void setTelefonos(Set telefonos) {
        this.telefonos = telefonos;
    }
    public Set getDocentes() {
        return this.docentes;
    }
    
    public void setDocentes(Set docentes) {
        this.docentes = docentes;
    }
    public Set getArchivoimagens() {
        return this.archivoimagens;
    }
    
    public void setArchivoimagens(Set archivoimagens) {
        this.archivoimagens = archivoimagens;
    }
    public Set getApoderados() {
        return this.apoderados;
    }
    
    public void setApoderados(Set apoderados) {
        this.apoderados = apoderados;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }
    public Set getTutors() {
        return this.tutors;
    }
    
    public void setTutors(Set tutors) {
        this.tutors = tutors;
    }




}


