package com.atlanta.educatic.pojo;
// Generated 14/01/2016 06:39:31 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tutor generated by hbm2java
 */
public class Tutor  implements java.io.Serializable {


     private int id;
     private Persona persona;
     private Tablamaestra tablamaestra;
     private Integer grado;
     private Set grados = new HashSet(0);

    public Tutor() {
    }

	
    public Tutor(int id, Persona persona) {
        this.id = id;
        this.persona = persona;
    }
    public Tutor(int id, Persona persona, Tablamaestra tablamaestra, Integer grado, Set grados) {
       this.id = id;
       this.persona = persona;
       this.tablamaestra = tablamaestra;
       this.grado = grado;
       this.grados = grados;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public Tablamaestra getTablamaestra() {
        return this.tablamaestra;
    }
    
    public void setTablamaestra(Tablamaestra tablamaestra) {
        this.tablamaestra = tablamaestra;
    }
    public Integer getGrado() {
        return this.grado;
    }
    
    public void setGrado(Integer grado) {
        this.grado = grado;
    }
    public Set getGrados() {
        return this.grados;
    }
    
    public void setGrados(Set grados) {
        this.grados = grados;
    }




}


