package com.atlanta.educatic.pojo;
// Generated 14/01/2016 06:39:31 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Vinculo generated by hbm2java
 */
public class Vinculo  implements java.io.Serializable {


     private int id;
     private Tablamaestra tablamaestra;
     private String denominacion;
     private String descripcion;
     private String observacion;
     private Set apoderados = new HashSet(0);

    public Vinculo() {
    }

	
    public Vinculo(int id, Tablamaestra tablamaestra, String denominacion) {
        this.id = id;
        this.tablamaestra = tablamaestra;
        this.denominacion = denominacion;
    }
    public Vinculo(int id, Tablamaestra tablamaestra, String denominacion, String descripcion, String observacion, Set apoderados) {
       this.id = id;
       this.tablamaestra = tablamaestra;
       this.denominacion = denominacion;
       this.descripcion = descripcion;
       this.observacion = observacion;
       this.apoderados = apoderados;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Tablamaestra getTablamaestra() {
        return this.tablamaestra;
    }
    
    public void setTablamaestra(Tablamaestra tablamaestra) {
        this.tablamaestra = tablamaestra;
    }
    public String getDenominacion() {
        return this.denominacion;
    }
    
    public void setDenominacion(String denominacion) {
        this.denominacion = denominacion;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public Set getApoderados() {
        return this.apoderados;
    }
    
    public void setApoderados(Set apoderados) {
        this.apoderados = apoderados;
    }




}


